        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE CALCPROFILE__genmod
          INTERFACE 
            SUBROUTINE CALCPROFILE(LUMENIN,SHELLIN,LUMENOUT,SHELLOUT)
              USE COMMONDEF
              TYPE (STREAMPROP), INTENT(IN) :: LUMENIN
              TYPE (STREAMPROP), INTENT(IN) :: SHELLIN
              TYPE (STREAMPROP), INTENT(OUT) :: LUMENOUT
              TYPE (STREAMPROP), INTENT(OUT) :: SHELLOUT
            END SUBROUTINE CALCPROFILE
          END INTERFACE 
        END MODULE CALCPROFILE__genmod
