        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE CALCSOUT__genmod
          INTERFACE 
            SUBROUTINE CALCSOUT(NCOMP,NMATE,INFLUENTS)
              INTEGER(KIND=4), INTENT(IN) :: NMATE
              INTEGER(KIND=4), INTENT(IN) :: NCOMP
              REAL(KIND=8), INTENT(IN) :: INFLUENTS(NCOMP,NMATE)
            END SUBROUTINE CALCSOUT
          END INTERFACE 
        END MODULE CALCSOUT__genmod
