        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE READSTREAM__genmod
          INTERFACE 
            SUBROUTINE READSTREAM(DATAFILENAME)
              CHARACTER(*), INTENT(IN) :: DATAFILENAME
            END SUBROUTINE READSTREAM
          END INTERFACE 
        END MODULE READSTREAM__genmod
