        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE READMOD__genmod
          INTERFACE 
            SUBROUTINE READMOD(DATAFILENAME)
              CHARACTER(*), INTENT(IN) :: DATAFILENAME
            END SUBROUTINE READMOD
          END INTERFACE 
        END MODULE READMOD__genmod
