        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_DQK15__genmod
          INTERFACE 
            SUBROUTINE TEST_DQK15
            END SUBROUTINE TEST_DQK15
          END INTERFACE 
        END MODULE TEST_DQK15__genmod
