        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_CALCPROFILE__genmod
          INTERFACE 
            SUBROUTINE TEST_CALCPROFILE
            END SUBROUTINE TEST_CALCPROFILE
          END INTERFACE 
        END MODULE TEST_CALCPROFILE__genmod
