        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_POWERFUNCTION_L__genmod
          INTERFACE 
            SUBROUTINE TEST_POWERFUNCTION_L(T)
              REAL(KIND=8) :: T
            END SUBROUTINE TEST_POWERFUNCTION_L
          END INTERFACE 
        END MODULE TEST_POWERFUNCTION_L__genmod
