        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_EFFECTIVEMOLARENTHALPY__genmod
          INTERFACE 
            SUBROUTINE TEST_EFFECTIVEMOLARENTHALPY
            END SUBROUTINE TEST_EFFECTIVEMOLARENTHALPY
          END INTERFACE 
        END MODULE TEST_EFFECTIVEMOLARENTHALPY__genmod
