        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_DAVG__genmod
          INTERFACE 
            SUBROUTINE TEST_DAVG
            END SUBROUTINE TEST_DAVG
          END INTERFACE 
        END MODULE TEST_DAVG__genmod
