        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_EFFTHERMALCONDUCTIVITY__genmod
          INTERFACE 
            SUBROUTINE TEST_EFFTHERMALCONDUCTIVITY
            END SUBROUTINE TEST_EFFTHERMALCONDUCTIVITY
          END INTERFACE 
        END MODULE TEST_EFFTHERMALCONDUCTIVITY__genmod
