        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_VAPORPRESSURE__genmod
          INTERFACE 
            SUBROUTINE TEST_VAPORPRESSURE
            END SUBROUTINE TEST_VAPORPRESSURE
          END INTERFACE 
        END MODULE TEST_VAPORPRESSURE__genmod
