        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_EFFECTIVEDIFFUSIVITY__genmod
          INTERFACE 
            SUBROUTINE TEST_EFFECTIVEDIFFUSIVITY
            END SUBROUTINE TEST_EFFECTIVEDIFFUSIVITY
          END INTERFACE 
        END MODULE TEST_EFFECTIVEDIFFUSIVITY__genmod
