        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:45 2016
        MODULE TEST_MOLARLATENTHEAT__genmod
          INTERFACE 
            SUBROUTINE TEST_MOLARLATENTHEAT
            END SUBROUTINE TEST_MOLARLATENTHEAT
          END INTERFACE 
        END MODULE TEST_MOLARLATENTHEAT__genmod
