        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:44 2016
        MODULE WRITEMOD__genmod
          INTERFACE 
            SUBROUTINE WRITEMOD(DATAFILENAME)
              CHARACTER(*), INTENT(IN) :: DATAFILENAME
            END SUBROUTINE WRITEMOD
          END INTERFACE 
        END MODULE WRITEMOD__genmod
