        !COMPILER-GENERATED INTERFACE MODULE: Thu Jan 07 16:05:44 2016
        MODULE WRITESTREAM__genmod
          INTERFACE 
            SUBROUTINE WRITESTREAM(DATAFILENAME)
              CHARACTER(*), INTENT(IN) :: DATAFILENAME
            END SUBROUTINE WRITESTREAM
          END INTERFACE 
        END MODULE WRITESTREAM__genmod
